### ISSUE TITLE
DiscardVirtualMemory not found in KERNEL32.dll when starting on Windows7

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [reorproject/reor#1]
Is the problem that im using Win7 ?

**Comment by samlhuillier** [comment]
Not been tested on win7 so couldn't say. Will test it this week and get back to you.

**Comment by samlhuillier** [comment]
I can confirm windows 7 is not supported. Just tested and replicated your error. It looks like sharp@0.32.6 (which is used by Lancedb) does not work on windows 7.
