### ISSUE TITLE
Error deleting items from DB: [Error: LanceDBError: LanceError(IO):

### ISSUE THREAD

**Issue by ElCuboNegro** [reorproject/reor#103]
System: Windows 11 Educational Edition (Windows 11 pro)

Steps to reproduce:
- Add a custom LLM using the steps in documentation. 
![image](https://github.com/reorproject/reor/assets/5524219/6eda8e65-164a-4b22-ba62-ca04bc5512a0)
- Pick Xenova/UAE-Large-V1
![image](https://github.com/reorproject/reor/assets/5524219/3b33b0f8-4267-45c7-96d9-881cc8ac4ca1)

Starting the dev enviroment it shows the following:

```

build started... (x2)
✓ 1 modules transformed.
dist-electron/preload/index.js  24.73 kB │ gzip: 6.59 kB │ map: 14.33 kB
built in 163ms.
✓ 112 modules transformed.
dist-electron/main/index.js  341.70 kB │ gzip: 66.32 kB │ map: 690.96 kB
built in 823ms.

Indexing files in directory
config is:  { type: 'repo', repoName: 'Xenova/UAE-Large-V1' }
getting files info list
Error deleting items from DB: [Error: LanceDBError: LanceError(IO): sql parser error: Expected an expression:, found: ), C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lance-0.9.16\src\utils\sql.rs:115:8]
```

Then, when I try to talk with the chat, the electron client becomes unresponsive.

![image](https://github.com/reorproject/reor/assets/5524219/683cf175-9e9b-4264-abd6-ee212bccd6c2)

THAT BEHAVIOR IS NOT CONSTANT and not always reproductible.

**Comment by samlhuillier** [comment]
Gotcha thanks for mentioning. The delete bug is non-breaking and should not affect any performance issues. As for the non-responding, it looks like perhaps your PC is not powerful enough to run mistral 7B...what kind of spec do you have? RAM, CPU, etc.

**Comment by ElCuboNegro** [comment]
![IMG-20240229-WA0160.jpg](https://github.com/reorproject/reor/assets/5524219/331d8cc9-0203-476c-bc14-1bc37ae4e51b)

**Comment by samlhuillier** [comment]
@ElCuboNegro if you now pull from main, you should not see this lancedb error in your logs anymore :)
