### ISSUE TITLE
upgrade from 1.5.2 to 1.5.3 then Error: Error in GetOrCreateLanceTable: Error: LanceDBError: LanceError(IO)

### ISSUE THREAD

**Issue by borpubi** [reorproject/reor#119]
**Describe the bug**
A description of what the bug is.

**To Reproduce**
1. upgrade from 1.5.2 to 1.5.3
2. open the soft
3. error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows11 23H2(22631.3235)
 - Version [e.g. 22] 1.5.2-->1.5.3

**Additional context**
Error: Error in GetOrCreateLanceTable: Error: LanceDBError: LanceError(IO): 系统找不到指定的文件。 (os error 2), C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lance-io-0.9.16\src\local.rs:50:5. Please try restarting or open a Github issue.

**Comment by borpubi** [comment]
When I run that in dev, it's looks like somethings incorrect install:
`Error: Embedding function error: Error: Resource initialization failed: Error: Something went wrong installing the "sharp" module Cannot find module '../build/Release/sharp-win32-x64.node' Require stack: - D:\Develop\reor\node_modules\@xenova\transformers\node_modules\sharp\lib\sharp.js - D:\Develop\reor\node_modules\@xenova\transformers\node_modules\sharp\lib\constructor.js - D:\Develop\reor\node_modules\@xenova\transformers\node_modules\sharp\lib\index.js Possible solutions: - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp" - Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp" - Consult the installation documentation: https://sharp.pixelplumbing.com/install. Please try downloading an embedding model from Hugging Face and attaching it in settings. More information can be found in settings.`

**Comment by samlhuillier** [comment]
@borpubi does downloading Reor from the downloads page work without error? It is only when you run Reor from ```npm run dev``` that it fails?

**Comment by borpubi** [comment]
When I run `npm install` I get like this:
`npm ERR! code 1
npm ERR! path D:\www\wegrow\node_modules\node-sass
npm ERR! command failed`
so I run `npm install --unsafe-perm`
looks like success.so I run 'npm run dev' get that error

**Comment by samlhuillier** [comment]
this is strange. To debug further can you confirm whether the windows download on [this page](https://github.com/reorproject/reor/releases/tag/v0.1.53) works and runs on your computer?

**Comment by borpubi** [comment]
> this is strange. To debug further can you confirm whether the windows download on [this page](https://github.com/reorproject/reor/releases/tag/v0.1.53) works and runs on your computer?

source code or exe file ?

**Comment by borpubi** [comment]
Ok, wait a moment.

**Comment by borpubi** [comment]
Got this error:
![image](https://github.com/reorproject/reor/assets/28093885/5ece73e8-7d49-4f7b-9aad-b1ae6fce713e)
but this path doesn't in my computer.
`C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lance-io-0.9.16\src\local.rs`

**Comment by borpubi** [comment]
I have a good try, renamed the foldername:
![image](https://github.com/reorproject/reor/assets/28093885/00b0f4a5-ac88-4d82-8c91-dcab75379922)
then, it's be run! 
But all config is lost and need to reindex.

**Comment by samlhuillier** [comment]
Gotcha. Does it work now?? Please confirm so that we can close this issue
