### ISSUE TITLE
npm run dev does nothing?

### ISSUE THREAD

**Issue by carcinocron** [reorproject/reor#121]
**Describe the bug**
`npm run dev` does nothing.

**To Reproduce**
Fresh install of repo with node@20 installed via homebrew.

output of `npm run dev`

```
build started... (x2)
✓ 1 modules transformed.
dist-electron/preload/index.js  25.82 kB │ gzip: 6.88 kB │ map: 14.86 kB
built in 75ms.
✓ 111 modules transformed.
dist-electron/main/index.js  336.50 kB │ gzip: 64.86 kB │ map: 677.41 kB
built in 589ms.
```

**Expected behavior**
thought some hotreloading thing would pop up

**Desktop (please complete the following information):**
 - OS: MacOS
- Hardware: M1 with 32GB RAM
 - Version: Sonoma 14.2.1 (23C71)

**Comment by chuyouchia** [comment]
Hi there, did you run `npm install` before running npm run dev?

**Comment by chuyouchia** [comment]
I tried reproducing it on my local with node v20.5.0 , but I wasn't able to. Could you add a video of your repo and local please?

**Comment by samlhuillier** [comment]
@carcinocron perhaps you have Reor running at the same time? This is quite common when you have the Reor executable that you downloaded running and you try to boot the dev version - so I'd suggest quitting Reor itself and try npm run dev again.

**Comment by carcinocron** [comment]
Looks like that was it, had the close the real build before `npm run dev` would open the dev build.
