### ISSUE TITLE
Related notes refresh button occasionally does not show up

### ISSUE THREAD

**Issue by samlhuillier** [reorproject/reor#150]
This happens when a user opens a newly created backlink:
<img width="399" alt="Screenshot 2024-04-08 at 12 48 54" src="https://github.com/reorproject/reor/assets/17236551/cf5e4825-9e08-4dbf-b27e-4b1c0a823be6">

**Comment by weilirs** [comment]
I can't reproduce the bug. The refresh button is always on the top right corner.

https://github.com/reorproject/reor/assets/62249815/019a47eb-5354-4cf3-afe3-01999579ced2

**Comment by samlhuillier** [comment]
@weilirs This is likely an old bug. Will close the issue for now :)
