### ISSUE TITLE
Content Length Indicator and Cursor Position Display

### ISSUE THREAD

**Issue by uuur86** [reorproject/reor#170]
By specifying that the content length indicator will display the number of characters and/or words for both the entire note and the selected portion, you provide a more comprehensive explanation of the feature's functionality. This distinction is important because it highlights the added benefit of being able to track the length of specific sections within a note, which can be particularly useful for editing and formatting purposes.

**Additional Idea: Cursor Position Display:** 
This feature would display the current line and character position of the cursor within the note. This can be helpful for navigating and editing longer notes, especially when precise positioning is required.

Thank you for considering this request.

**Comment by samlhuillier** [comment]
Thank you for opening this. I think building logic around handling cursor position could be useful for a slightly different reason to what you mention: we can use where the user's cursor is to direct related notes to show only notes related to the block in the note the user's cursor is on. This will help focus the semantic lookup which I think will lead to higher quality related notes. What do you think about that?
