### ISSUE TITLE
Operation not permitted in rename of directory with children on windows

### ISSUE THREAD

**Issue by samlhuillier** [reorproject/reor#174]
<img width="609" alt="Screenshot 2024-03-30 at 13 52 49" src="https://github.com/reorproject/reor/assets/17236551/b03a6121-797c-4125-8393-1294fb9d9f3c">

The above error happens when a user tries to rename a directory on Windows that has children in it. I suspect this is because Reor is locking the files and we need to do something to unlock/unwatch the files when doing the rename operation. More research on this is required though

**Comment by milaiwi** [comment]
I'll go ahead and take a look and see what I can get done on this!

**Comment by milaiwi** [comment]
I went ahead and made a pull request for this. Seems like windows does not allow rename operations when the file is open, and in this case that required unwatching the vault. I simply checked if the user was running on a windows environment and did the necessary steps. Let me know if this is aligned with what you were thinking or some issues that you think this could allow. Thanks!
