### ISSUE TITLE
Reor dock icon is larger than other icons.

### ISSUE THREAD

**Issue by bearwithtea** [reorproject/reor#184]
The Reor icon appears to be larger than every other icon on the dock, which is visually unappealing.

**Describe the solution you'd like**
It would be nice for it to be a little bit smaller!

**Additional context**
Running this on an 2020 M1 Air, latest Reor release.

![CleanShot 2024-04-04 at 08 40 52@2x](https://github.com/reorproject/reor/assets/132114816/aaad011a-7215-497b-9515-24c3f0f93984)

**Comment by samlhuillier** [comment]
Yes that'd be great if you could push that up as a PR!

**Comment by bearwithtea** [comment]
Alright, I will get that done tonight!

**Comment by prasadshreyas** [comment]
The Reor icon defaults to electron icon.

Additional context
2021 M1 Pro, latest Reor release

<img width="203" alt="Screenshot 2024-04-04 at 7 36 35 PM" src="https://github.com/reorproject/reor/assets/50020957/a309ef89-53e1-4a8e-b056-50e3dc92e440">

**Comment by bearwithtea** [comment]
@samlhuillier 

Alright, I just fired it off. I am still really new to open source in general, so please let me know if I messed anything up. I am happy to fix it and learn!

**Comment by bearwithtea** [comment]
@prasadshreyas 

Oh, that is interesting, I am not sure why that would be. Mine is still the Reor icon...

**Comment by bearwithtea** [comment]
@prasadshreyas Sounds good!
