### ISSUE TITLE
Show note name in related notes sidebar and search results

### ISSUE THREAD

**Issue by samlhuillier** [reorproject/reor#189]
It would be nice to see which note a chunk that has been matched as similar belongs to. To do this, the react code in ```DBResultPreview.tsx``` should be modified: there is one component for similar sidebar results ```DBResultPreview``` and another for search results ```DBSearchPreview```.

**Comment by milaiwi** [comment]
Are you saying you'd want to see the path of the chunk that pops up in the related notes sidebar or just the name of the file? If it's the path, should it be relative or absolute?

**Comment by samlhuillier** [comment]
It would just be either the filename I think. We could think about a relative path but given the limited screen estate, filename would be the best imo. Would love to see a contribution here! Let me know if you're interested, very happy to help out & review any PRs :)

**Comment by milaiwi** [comment]
Thanks for the response! I made a PR for what I believe this issue was trying to do. I couldn't find information for how that commit message should look so let me know if I need to change anything!
