### ISSUE TITLE
[Feature request] Don't import non-markdown files

### ISSUE THREAD

**Issue by ke1ne** [reorproject/reor#19]
Hi, guys!

1. During the notes import, please add some filter to avoid trying to load non-md files. I've imported a bunch of PDF by accident, and the app has nothing to do with them.
2. Add some more obvious indication in the import UI that mentions Reor doesnt's work with other file types.

Thank you!

**Comment by samlhuillier** [comment]
Thank you for making this request! It should now be fixed in the [latest release(https://github.com/reorproject/reor/releases/tag/v0.1.40).
