### ISSUE TITLE
Support changing chunk size & chunking scheme in settings

### ISSUE THREAD

**Issue by samlhuillier** [reorproject/reor#193]
Chunk size is currently 500. This should not be hardcoded and users should be able to change this in settings. 

Implementation:
1. Add the property in store config for chunk size
2. Use chunk size in ```Chunking.ts```
3. Add a page in settings to change this chunk size

An extension of this would be to change the chunking scheme; right now, markdown headings with # start a new note. Some users may not want that.

**Comment by milaiwi** [comment]
Inside `Chunking.ts`, should we create a `new Store<StoreSchema>()` or modify the function to take in a pre-existing `store`, similar to how other functions do it?

**Comment by milaiwi** [comment]
Any update on this?
