### ISSUE TITLE
Fix spacing in react markdown for sidebar/search components

### ISSUE THREAD

**Issue by samlhuillier** [reorproject/reor#205]
Visible here:
![Screenshot 2024-04-19 at 11 31 20](https://github.com/reorproject/reor/assets/17236551/8f66b478-dfaa-4f09-84b6-58676b28d501)

**Comment by weilirs** [comment]
<img width="288" alt="image" src="https://github.com/user-attachments/assets/beca351b-4a9c-4880-bb38-333950e20b44">
fixed
