### ISSUE TITLE
Fix indentation in similar files sidebar

### ISSUE THREAD

**Issue by samlhuillier** [reorproject/reor#212]
This happens when there bullet point indentation in the react markdown sidebar:
<img width="277" alt="Screenshot 2024-04-21 at 18 32 39" src="https://github.com/reorproject/reor/assets/17236551/4751800b-8f0d-42a5-b07c-aaad57ba8eb7">

**Comment by tusharkaran** [comment]
is it fixed ? Can i work on it ?

**Comment by weilirs** [comment]
> is it fixed ? Can i work on it ?

I believe it has been fixed. However, we have other "good first issues" available if you'd like to contribute! Additionally, you can work on any issue, whether or not it is labeled as a "good first issue," even if this is your initial contribution.

**Comment by tusharkaran** [comment]
can we tell tell me any good first issue , I am new to open source contrubtion , would really appreciate if you can provide me any issue  which is not fixed.

**Comment by weilirs** [comment]
![image](https://github.com/user-attachments/assets/96421e69-4dee-45df-bbfc-bc704f79bcc4)
You can filter the "label" to see what are good first issues.

**Comment by weilirs** [comment]
Or do you want to work on this one? @tusharkaran  
This will be a cool feature for Reor
https://github.com/reorproject/reor/issues/286

**Comment by tusharkaran** [comment]
Sure
