### ISSUE TITLE
Improvement requests

### ISSUE THREAD

**Issue by joelawrence121** [reorproject/reor#23]
### Github flavoured markdown
Tick boxes are not tacit 

![Screenshot 2024-02-05 at 10 50 12](https://github.com/reorproject/reor/assets/32837058/ee621709-2fd6-4e8f-af39-afc7bd59c2a6)

### Default prompt
Seems the retrieval prompt is just repeated if something not expected is asked of the LLM 

![Screenshot 2024-02-05 at 17 46 33](https://github.com/reorproject/reor/assets/32837058/95562765-d8c1-463f-809f-b4d83305addf)

### Creating links 
Writing links any other way than 1. [ 2. text 3. ] 4. ( 5. link 6. ) or pasting it is impossible. The placeholders should remain if they are blank `[]()`

### Similarity measure 

![Screenshot 2024-02-05 at 17 50 16](https://github.com/reorproject/reor/assets/32837058/4fafd9d4-4bfb-4818-adf7-2af3d719d960)

A percentage calculation on page similarity is non-intuitive. Would be nice to see the semantic properties that contribute to a high similarity measure: `productivity, software engineering etc...`

**Comment by samlhuillier** [comment]
Dear @joelawrence121. Thank you for making this issue! 

1. Tickboxes right now can be made with [ ] on a new line.
    - In the coming days, I am switching editor plugin to enable more native markdown features like - [ ] + AI writing assistance.

2. If the model is outputting the prompt rather than answering the question, this is more than likely caused by the model's own capabilities rather than the prompt itself. Which model are you using? Perhaps you could try using a bigger one like [Llama 2 13B](https://huggingface.co/TheBloke/Llama-2-13B-GGUF/blob/main/llama-2-13b.Q4_K_M.gguf)?

3. Similarity is calculated via an embedding model right now which does not provide any kind of way of extracting properties. 
    - I have thought about some kind of strategy that preemptively tags notes with properties generated by an LLM, or at runtime adds extra "semantic properties" in the sidebar - though right now I suspect that the computational cost of doing this would be too significant to make it worthwhile. Perhaps you have an idea or suggestion on this?

**Comment by joelawrence121** [comment]
On 4) the way I would do it is as you say, reduce each note to a set of tags (which could be done as a background task avoiding user latency). Append that to a list of user tags pooled from each note and compare the embeddings of a note to the embeddings of the tag. This would give you some notion of an embedding -> word mapping. 

How to optimise and maintain the list of tags is a different beast. Maybe ask @Matthew Tichborne

**Comment by joelawrence121** [comment]
@samlhuillier is it possible to change directory / open a new directory? Can easily change models in settings but not this.

**Comment by samlhuillier** [comment]
Not yet. On my todo list. Will aim to get it out this weekend

**Comment by samlhuillier** [comment]
Now available in the new release: https://github.com/reorproject/reor/releases/tag/v0.1.47
