### ISSUE TITLE
macOS Intel version does not work

### ISSUE THREAD

**Issue by wenlzhang** [reorproject/reor#230]
Somehow macOS Intel app in the 0.2.4 and 0.2.5 releases cannot be opened.
```
You can't open the application
"Reor.app" because this
application is not supported on
this Mac.
```

**Comment by cliffordx** [comment]
I got the same error. I rolled back to earlier version until the next  update

**Comment by samlhuillier** [comment]
@cliffordx @wenlzhang thanks for raising this. We've pushed a [new release](https://github.com/reorproject/reor/releases/tag/v0.2.6) where hopefully this should be fixed :)
