### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by zysimplelife** [reorproject/reor#234]
**Is your feature request related to a problem? Please describe.**
This is very nice setup and I found it is useful project.  I understand it is in the start point of missing some fundamental features. 
One of them is the keyboard shortcut for some quite often used editor features like 

* Search files (not content).  In VS code, there is ctrl + p in windows to open a command table to search file
* Jump back and forward.   Using mouse is kind of inconvenient.
* Create a new note shortcut. 

**Describe the solution you'd like**
Add default mapping as short term solution

Thanks again for the great work.

**Comment by subin-chella** [comment]
@joseplayero Kindly chek both the PR and suggest which way we want to implement.
