### ISSUE TITLE
Crashing when attempting to initialise the database

### ISSUE THREAD

**Issue by timuryung** [reorproject/reor#24]
The app crashes while attempting to initialise the vector database.

OS: Windows 11
App version: 0.1.40

**Comment by samlhuillier** [comment]
Thank you for reporting! 
Would you be able to get the logs of this when it happens by say running the app in a terminal?
Also, to gauge whether this is a hardware issue, what CPU and RAM does you system have?

**Comment by timuryung** [comment]
Not sure how to run app in Terminal, My CPU and RAM are not so good, but the problem is that it was at least loading before but latest version don't even load on Windows 11.

**Comment by samlhuillier** [comment]
Gotcha. Could you try building from source?
Instructions are as follows:
1. Download and install [git](https://git-scm.com/download/win) and [node](https://nodejs.org/en/download).
2. Open powershell then run the following:

```
git clone https://github.com/reorproject/reor
```
```
cd reor
```
```
npm install
```
```
npm run dev
```

That should run Reor from source and you should be able to see logs right from powershell. Would be great if you could send those logs over to me :)

**Comment by timuryung** [comment]
Here are the logs: Path does not exist: C:\Users\Timur Yun\Desktop\notes
dbPath:  C:\Users\Timur Yun\AppData\Roaming\Reor\vectordb
Path does not exist: C:\Users\Timur Yun\Desktop\notes

I think the problem is in space in the path

**Comment by samlhuillier** [comment]
It just crashes straight after these logs with no explanation?
I just tried something similar and I get the following:
```
Path does not exist: C:\Users\Sam Lhuillier\Documents\test
no items to add
Path does not exist: C:\Users\Sam Lhuillier\Documents\test
Path does not exist: C:\Users\Sam Lhuillier\Documents\test
```
But it does continue into boot and everything (I deleted my vault dir to simulate this). It is strange that yours is crashing like this because if there are no files found, it shouldn't start embedding and indexing anything...

**Comment by timuryung** [comment]
Yes, it's strange. It crashes straight after these logs.

**Comment by samlhuillier** [comment]
Could we debug this together over a quick call perhaps?
https://cal.com/lhuillier

**Comment by samlhuillier** [comment]
I've just added some more logging to the part of the code I suspect is causing this error. Would you be able to pull and rerun it to get those logs for me?
```
git pull
npm run dev
```
If you prefer, feel free to email me those logs too: samlhuillier1@gmail.com

**Comment by timuryung** [comment]
Here is the log before the app crashes
vite v4.5.2 building for development...

watching for file changes...
vite v4.5.2 building for development...

watching for file changes...

build started...

build started... (x2)
✓ 1 modules transformed.
dist-electron/preload/index.js  20.89 kB │ gzip: 6.01 kB │ map: 12.06 kB
built in 797ms.
✓ 107 modules transformed.
dist-electron/main/index.js  291.74 kB │ gzip: 57.22 kB │ map: 606.73 kB
built in 3688ms.

dbPath:  C:\Users\Timur Yun\AppData\Roaming\Reor\vectordb
dbConnection:  LocalConnection {
  _options: [Function (anonymous)],
  _db: [External: 2368c9cb3d0]
}
Intended schema: Schema {
  fields: [
    Field {
      name: 'notepath',
      type: Utf8 {},
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'vector',
      type: [FixedSizeList],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'content',
      type: Utf8 {},
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'subnoteindex',
      type: [Float64 [Float]],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'timeadded',
      type: [Date_ [Date]],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'filemodified',
      type: [Date_ [Date]],
      nullable: false,
      metadata: Map(0) {}
    }
  ],
  metadata: Map(0) {},
  dictionaries: Map(0) {},
  metadataVersion: 4
}
initialized:  LanceDBTableWrapper {
  table: LocalTable {
    where: [Function: filter],
    _tbl: [External: 23695657590],
    _name: 'ragnote_table_Xenova_bge-base-en-v1.5_C__Users_Timur Yun_Desktop_notes',
    _embeddings: {
      name: 'Xenova/bge-base-en-v1.5',
      contextLength: 768,
      sourceColumn: 'content',
      embed: [AsyncFunction: embed],
      tokenize: [Function: tokenize]
    },
    _options: [Function (anonymous)],
    _isElectron: true
  },
  embedFun: {
    name: 'Xenova/bge-base-en-v1.5',
    contextLength: 768,
    sourceColumn: 'content',
    embed: [AsyncFunction: embed],
    tokenize: [Function: tokenize]
  }
}
got files info list:  1
files info tree length:  {
  name: 'test.md',
  path: 'C:\\Users\\Timur Yun\\Desktop\\notes\\test.md',
  relativePath: 'test.md',
  dateModified: 2024-02-08T22:36:47.852Z
}

**Comment by samlhuillier** [comment]
Thank you! I think I've isolated it the issue to the function getTableAsArray and I suspect it's because of Lancedb updates. Could you git pull and run it again?

**Comment by timuryung** [comment]
Here are the logs
dbPath:  C:\Users\Timur Yun\AppData\Roaming\Reor\vectordb
dbConnection:  LocalConnection {
  _options: [Function (anonymous)],
  _db: [External: 22f135fe570]
}
Intended schema: Schema {
  fields: [
    Field {
      name: 'notepath',
      type: Utf8 {},
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'vector',
      type: [FixedSizeList],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'content',
      type: Utf8 {},
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'subnoteindex',
      type: [Float64 [Float]],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'timeadded',
      type: [Date_ [Date]],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'filemodified',
      type: [Date_ [Date]],
      nullable: false,
      metadata: Map(0) {}
    }
  ],
  metadata: Map(0) {},
  dictionaries: Map(0) {},
  metadataVersion: 4
}
initialized:  LanceDBTableWrapper {
  table: LocalTable {
    where: [Function: filter],
    _tbl: [External: 22f15c41f30],
    _name: 'ragnote_table_Xenova_bge-base-en-v1.5_C__Users_Timur Yun_Desktop_notes',
    _embeddings: {
      name: 'Xenova/bge-base-en-v1.5',
      contextLength: 768,
      sourceColumn: 'content',
      embed: [AsyncFunction: embed],
      tokenize: [Function: tokenize]
    },
    _options: [Function (anonymous)],
    _isElectron: true
  },
  embedFun: {
    name: 'Xenova/bge-base-en-v1.5',
    contextLength: 768,
    sourceColumn: 'content',
    embed: [AsyncFunction: embed],
    tokenize: [Function: tokenize]
  }
}
got files info list:  1
files info tree length:  {
  name: 'test.md',
  path: 'C:\\Users\\Timur Yun\\Desktop\\notes\\test.md',
  relativePath: 'test.md',
  dateModified: 2024-02-08T22:36:47.852Z
}
starting table count:
total rows:  1
non empty results:  1
empty results:  0
concated results:  1
got table as array: 1
table array:  {
  notepath: 'C:\\Users\\Timur Yun\\Desktop\\notes\\test.md',
  vector: [
     -0.021381141617894173,   0.017731627449393272,    0.02069319784641266,
      0.012781749479472637,   0.033809054642915726,  -0.010082274675369263,
       0.04500329867005348,  -0.005608477164059877,  -0.020592663437128067,
      -0.04407056048512459,   0.008413226343691349,  -0.004235122352838516,
      -0.04652830958366394,   0.022403713315725327,    0.06450934708118439,
       0.06118214502930641,    0.07074735313653946,   0.021809518337249756,
       0.05491763353347778,  -0.012670516036450863, -0.0063097067177295685,
     -0.046841200441122055,   0.009678262285888195,    0.05276259779930115,
       0.03486562892794609,   0.003029509913176298,   0.040111154317855835,
     -0.018189385533332825,    -0.0379800908267498,   -0.05401827022433281,
      0.030961209908127785,   0.023539267480373383,    0.00907051470130682,
     -0.004003406967967749,   0.013370301574468613,  -0.019606783986091614,
     -0.046246882528066635,  0.0019968333654105663,  -0.003905360121279955,
     -0.016099900007247925,   -0.06893689185380936,  -0.056666407734155655,
     0.0020996907260268927, -0.0038612845819443464,  -0.007471887394785881,
     -0.036859042942523956,   0.013610576279461384,     0.0176024679094553,
       0.03224683925509453,  -0.007256814744323492,   -0.05573618784546852,
     -0.009567436762154102,    0.06563729792833328,   0.028496749699115753,
      -0.03027043305337429,   0.026235776022076607,  0.0008408097201026976,
     0.0026711500249803066,   0.012393536977469921,   -0.05455886945128441,
       0.04393796622753143,   0.012550781480967999,    0.03437400981783867,
      0.002231224672868848,    0.05830587074160576,   0.034091316163539886,
     -0.016138676553964615,   0.006901610642671585,   -0.03299599885940552,
     -0.014653331600129604,    0.00536500196903944,  -0.009004958905279636,
    -0.0005994102102704346,   -0.04986102506518364,   0.035809021443128586,
      -0.02390517108142376,     0.0422554574906826,  -0.011630469933152199,
       0.05797071382403374,   -0.03365505859255791,  0.0001766482600942254,
     -0.012960142455995083,   -0.02700970321893692,   0.053425293415784836,
     -0.008660835213959217,     -0.041488166898489,   -0.02072322368621826,
      0.053124845027923584,  -0.047994472086429596,    0.04929649084806442,
     -0.011768448166549206,  -0.013665486127138138,   0.045621953904628754,
       0.05729715898633003,   0.011044437997043133,  -0.016849268227815628,
        0.0360344834625721,  -0.016727300360798836,    0.03128453716635704,
     -0.029848147183656693,
    ... 668 more items
  ],
  content: 'asdsadsad\n',
  subnoteindex: 0,
  timeadded: 2024-02-08T22:36:47.880Z,
  filemodified: 2024-02-08T22:36:47.880Z
}
got db items to add:  0
no items to add
repopulated:  LanceDBTableWrapper {
  table: LocalTable {
    where: [Function: filter],
    _tbl: [External: 22f15c41f30],
    _name: 'ragnote_table_Xenova_bge-base-en-v1.5_C__Users_Timur Yun_Desktop_notes',
    _embeddings: {
      name: 'Xenova/bge-base-en-v1.5',
      contextLength: 768,
      sourceColumn: 'content',
      embed: [AsyncFunction: embed],
      tokenize: [Function: tokenize]
    },
    _options: [Function (anonymous)],
    _isElectron: true
  },
  embedFun: {
    name: 'Xenova/bge-base-en-v1.5',
    contextLength: 768,
    sourceColumn: 'content',
    embed: [AsyncFunction: embed],
    tokenize: [Function: tokenize]
  }
}

**Comment by timuryung** [comment]
After this the app is crashes

**Comment by timuryung** [comment]
Interestingly it crashes when I finishing typing in the note

**Comment by samlhuillier** [comment]
Gotcha so we're making progress! I've added some more error catching and logging - could you try again and shoot over the logs?

**Comment by timuryung** [comment]
Here are the latest logs
Path does not exist: C:\Users\Timur Yun\Desktop\notes
dbPath:  C:\Users\Timur Yun\AppData\Roaming\Reor\vectordb
dbConnection:  LocalConnection {
  _options: [Function (anonymous)],
  _db: [External: 225a387fc40]
}
Intended schema: Schema {
  fields: [
    Field {
      name: 'notepath',
      type: Utf8 {},
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'vector',
      type: [FixedSizeList],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'content',
      type: Utf8 {},
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'subnoteindex',
      type: [Float64 [Float]],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'timeadded',
      type: [Date_ [Date]],
      nullable: false,
      metadata: Map(0) {}
    },
    Field {
      name: 'filemodified',
      type: [Date_ [Date]],
      nullable: false,
      metadata: Map(0) {}
    }
  ],
  metadata: Map(0) {},
  dictionaries: Map(0) {},
  metadataVersion: 4
}
initialized:  LanceDBTableWrapper {
  table: LocalTable {
    where: [Function: filter],
    _tbl: [External: 225ad09ca70],
    _name: 'ragnote_table_Xenova_bge-base-en-v1.5_C__Users_Timur Yun_Desktop_notes',
    _embeddings: {
      name: 'Xenova/bge-base-en-v1.5',
      contextLength: 768,
      sourceColumn: 'content',
      embed: [AsyncFunction: embed],
      tokenize: [Function: tokenize]
    },
    _options: [Function (anonymous)],
    _isElectron: true
  },
  embedFun: {
    name: 'Xenova/bge-base-en-v1.5',
    contextLength: 768,
    sourceColumn: 'content',
    embed: [AsyncFunction: embed],
    tokenize: [Function: tokenize]
  }
}
Path does not exist: C:\Users\Timur Yun\Desktop\notes
got files info list:  0
starting table count:
total rows:  2
non empty results:  2
empty results:  0
concated results:  2
got table as array: 2
table array:  {
  notepath: 'C:\\Users\\Timur Yun\\Desktop\\notes\\test.md',
  vector: [
     -0.021381141617894173,   0.017731627449393272,    0.02069319784641266,
      0.012781749479472637,   0.033809054642915726,  -0.010082274675369263,
       0.04500329867005348,  -0.005608477164059877,  -0.020592663437128067,
      -0.04407056048512459,   0.008413226343691349,  -0.004235122352838516,
      -0.04652830958366394,   0.022403713315725327,    0.06450934708118439,
       0.06118214502930641,    0.07074735313653946,   0.021809518337249756,
       0.05491763353347778,  -0.012670516036450863, -0.0063097067177295685,
     -0.046841200441122055,   0.009678262285888195,    0.05276259779930115,
       0.03486562892794609,   0.003029509913176298,   0.040111154317855835,
     -0.018189385533332825,    -0.0379800908267498,   -0.05401827022433281,
      0.030961209908127785,   0.023539267480373383,    0.00907051470130682,
     -0.004003406967967749,   0.013370301574468613,  -0.019606783986091614,
     -0.046246882528066635,  0.0019968333654105663,  -0.003905360121279955,
     -0.016099900007247925,   -0.06893689185380936,  -0.056666407734155655,
     0.0020996907260268927, -0.0038612845819443464,  -0.007471887394785881,
     -0.036859042942523956,   0.013610576279461384,     0.0176024679094553,
       0.03224683925509453,  -0.007256814744323492,   -0.05573618784546852,
     -0.009567436762154102,    0.06563729792833328,   0.028496749699115753,
      -0.03027043305337429,   0.026235776022076607,  0.0008408097201026976,
     0.0026711500249803066,   0.012393536977469921,   -0.05455886945128441,
       0.04393796622753143,   0.012550781480967999,    0.03437400981783867,
      0.002231224672868848,    0.05830587074160576,   0.034091316163539886,
     -0.016138676553964615,   0.006901610642671585,   -0.03299599885940552,
     -0.014653331600129604,    0.00536500196903944,  -0.009004958905279636,
    -0.0005994102102704346,   -0.04986102506518364,   0.035809021443128586,
      -0.02390517108142376,     0.0422554574906826,  -0.011630469933152199,
       0.05797071382403374,   -0.03365505859255791,  0.0001766482600942254,
     -0.012960142455995083,   -0.02700970321893692,   0.053425293415784836,
     -0.008660835213959217,     -0.041488166898489,   -0.02072322368621826,
      0.053124845027923584,  -0.047994472086429596,    0.04929649084806442,
     -0.011768448166549206,  -0.013665486127138138,   0.045621953904628754,
       0.05729715898633003,   0.011044437997043133,  -0.016849268227815628,
        0.0360344834625721,  -0.016727300360798836,    0.03128453716635704,
     -0.029848147183656693,
    ... 668 more items
  ],
  content: 'asdsadsad\n',
  subnoteindex: 0,
  timeadded: 2024-02-08T22:36:47.880Z,
  filemodified: 2024-02-08T22:36:47.880Z
}
got db items to add:  0
no items to add
repopulated:  LanceDBTableWrapper {
  table: LocalTable {
    where: [Function: filter],
    _tbl: [External: 225ad09ca70],
    _name: 'ragnote_table_Xenova_bge-base-en-v1.5_C__Users_Timur Yun_Desktop_notes',
    _embeddings: {
      name: 'Xenova/bge-base-en-v1.5',
      contextLength: 768,
      sourceColumn: 'content',
      embed: [AsyncFunction: embed],
      tokenize: [Function: tokenize]
    },
    _options: [Function (anonymous)],
    _isElectron: true
  },
  embedFun: {
    name: 'Xenova/bge-base-en-v1.5',
    contextLength: 768,
    sourceColumn: 'content',
    embed: [AsyncFunction: embed],
    tokenize: [Function: tokenize]
  }
}
Path does not exist: C:\Users\Timur Yun\Desktop\notes
Path does not exist: C:\Users\Timur Yun\Desktop\notes
Creating file C:\Users\Timur Yun\Desktop\notes\asd.md
Writing file C:\Users\Timur Yun\Desktop\notes\asd.md
Done writing file C:\Users\Timur Yun\Desktop\notes\asd.md
Deleting items from DB with paths: 'C:\Users\Timur Yun\Desktop\notes\asd.md'
Filter string: notepath IN ('C:\Users\Timur Yun\Desktop\notes\asd.md')
Done deleting items from DB
starting chunk
done chunk
db entreis:  1
Adding data to DB:
first item:  {
  notepath: 'C:\\Users\\Timur Yun\\Desktop\\notes\\asd.md',
  content: 'asdsadasd\n\nasdasd\n\n\n\n',
  subnoteindex: 0,
  timeadded: 2024-02-09T16:24:50.570Z,
  filemodified: 2024-02-09T16:24:50.570Z
}
Chunks:
first chunk:  [
  {
    notepath: 'C:\\Users\\Timur Yun\\Desktop\\notes\\asd.md',
    content: 'asdsadasd\n\nasdasd\n\n\n\n',
    subnoteindex: 0,
    timeadded: 2024-02-09T16:24:50.570Z,
    filemodified: 2024-02-09T16:24:50.570Z
  }
]
Adding chunk to DB:
Done adding chunk to DB

**Comment by timuryung** [comment]
After these lines the app crashes

**Comment by timuryung** [comment]
Oh, it seems like this is the issue only with one specific system. I tried it on the fresh system and it works as expected. This is probably because there are too much applications on the system where the problem appeared. I'm sorry for inconvenience.

**Comment by samlhuillier** [comment]
Ah no problem! Do you have any feedback on Reor? Anything you liked/didn't like or would want to see?

**Comment by timuryung** [comment]
Everything is OK! Thank for your time!
