### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by Timothychen00** [reorproject/reor#254]
**Describe the bug**
the reorproject.org is
 down.

**To Reproduce**
1. Go to reorproject.org

**Expected behavior**
see the webpage

**Screenshots**
![IMG_6506](https://github.com/reorproject/reor/assets/52665482/ea6671b6-760d-4038-9957-888a3fcbb0eb)

**Comment by samlhuillier** [comment]
Thanks for mentioning! This is has been fixed :)
