### ISSUE TITLE
stuck in "initalizing vecotor database"

### ISSUE THREAD

**Issue by wynemo** [reorproject/reor#265]
**stuck in "initalizing vecotor database"**
A description of what the bug is.

**To Reproduce**
1. attach local LLM(ollama)
2. select a local note folder
3. stuck in "initalizing vecotor database"

**Screenshots**
<img width="700" alt="image" src="https://github.com/reorproject/reor/assets/1314428/c12d2d88-2674-45c6-acdc-8a0fe69607df">

**Desktop (please complete the following information):**
 - OS: macos 14
- Hardware: apple m2

**Comment by samlhuillier** [comment]
This step is downloading an embedding model. Perhaps check if wifi is an issue and restart the app?

**Comment by wynemo** [comment]
it would open after some time

**Comment by samlhuillier** [comment]
Do you have lots of files in your vault?
