### ISSUE TITLE
Change main directory path | Reset Reor

### ISSUE THREAD

**Issue by sebastienfi** [reorproject/reor#279]
**Is your feature request related to a problem? Please describe.**
I selected a main directory during setup, while testing Reor. Now that I decided I want to use Reor, I would like to change my main folder. Mainly, I didn't realised that everything in the selected folder would be indexed, and I selected my Documents folder on MacOS. 

**Describe the solution you'd like**
On the settings, have a option to change the folder, or a command to reset Reor to its factory settings (this would delete any index).

**Comment by samlhuillier** [comment]
Please use this button in the bottom left corner to open a new window and directory:
<img width="48" alt="Screenshot 2024-06-18 at 23 11 30" src="https://github.com/reorproject/reor/assets/17236551/2d16896f-c3fa-443a-ab0a-f59a23e214fa">
