### ISSUE TITLE
`lancedb/vectordb-win32-x64-msvc` is incompatible with ARM64

### ISSUE THREAD

**Issue by weilirs** [reorproject/reor#282]
**Describe the bug**
` "@lancedb/vectordb-win32-x64-msvc": "^0.5.0",` this package in `package.json`
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS]
- Hardware: [Apple Silicon]

**Additional context**

**Comment by samlhuillier** [comment]
Is this for the latest release executable or when you try to run the npm repo?

**Comment by weilirs** [comment]
run the npm repo on the latest commit

**Comment by samlhuillier** [comment]
Ok thanks @weilirs this'll be fixed before the next release :)
