### ISSUE TITLE
[Code Suggestion] Improve File and Folder Creation to Respect Selected Path

### ISSUE THREAD

**Issue by sebastienfi** [reorproject/reor#284]
**Description**: 
When creating a new file or a new folder, the application should consider the selected folder or file path for the creation of the new file or folder. Currently, a new file or folder is always placed at the root, which is inconvenient as users need to move it to the desired location by drag-and-drop.

**Requirements**:
- The new file or folder should be created in the currently selected folder or at the same level as the currently selected file.
- If no folder or file is selected, the new file or folder should be created at the root.

**Proposed implementation**:
- **Change 1**: Update the logic for creating new files in `NewNoteComponent.tsx`

**NewNoteComponent.tsx**:
```typescript
const sendNewNoteMsg = async () => {
  if (!fileName || errorMessage) {
    return;
  }
  const selectedPath = await window.electronStore.getSelectedPath();
  const fullPath = selectedPath ? `${selectedPath}/${fileName}` : fileName;
  openRelativePath(fullPath);
  posthog.capture("created_new_note_from_new_note_modal")
  onClose();
};
```
- **Change 2**: Update the logic for creating new folders in `NewDirectoryComponent.tsx`

**NewDirectoryComponent.tsx**:
```typescript
const sendNewDirectoryMsg = async () => {
  try {
    if (!directoryName || errorMessage) {
      return;
    }
    const selectedPath = await window.electronStore.getSelectedPath();
    const fullPath = selectedPath ? `${selectedPath}/${directoryName}` : directoryName;
    window.files.createDirectory(fullPath);
    posthog.capture("created_new_directory_from_new_directory_modal");
    onDirectoryCreate(fullPath);
    onClose();
  } catch (e) {
    toast.error(errorToString(e), {
      className: "mt-5",
      autoClose: false,
      closeOnClick: false,
      draggable: false,
    });
  }
};
```

**Tasks required**:
- Update `NewNoteComponent.tsx` to use the selected path for new file creation.
- Update `NewDirectoryComponent.tsx` to use the selected path for new folder creation.
- Ensure that the selected path is correctly retrieved and used in both components.
- Test the changes to ensure that new files and folders are created in the correct locations.

**Benefits**:
- Improved user experience by reducing the need to manually move newly created files and folders.
- Increased efficiency in file and folder management within the application.
- Alignment with user expectations for file and folder creation behavior.

**Comment by milaiwi** [comment]
Thanks for the suggestion and outline! I definitely agree with you and will make a PR tonight.

**Comment by sebastienfi** [comment]
It works! Nice work
