### ISSUE TITLE
Use a mirror for embedding model

### ISSUE THREAD

**Issue by ZeroCore-Zero** [reorproject/reor#285]
**Is your feature request related to a problem? Please describe.**
Due to my poor network conditions, i need to use a mirror of huggingface instead of the official one. However i can't find a setting to do this.

**Describe the solution you'd like**
Allow users switch the model download source on the page of create a new vault, or let users input a full URL address rather than just a name.

**Additional context**
BYW, can this suggestion also work in the llm setting?

**Comment by samlhuillier** [comment]
Unfortunately right now the only solution would be to attach your own local embedding model following these instructions: https://www.reorproject.org/docs/documentation/embedding
