### ISSUE TITLE
A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by xuquankun** [reorproject/reor#291]
Uncaught Exception:
Error:vectordb:failed to load native library.
You may need to run 'npm install @lancedb/vectordb-win32-x64-msvc'
if that does not work, please file a bug report at 
https://github.com/lancedb/lancedb/issues
source error: Error: Cannot find module '@lancedb/vectordb-win32-x64-msvc'
Require stact:

**Comment by samlhuillier** [comment]
This should be fixed! Feel free to reopen if not
