### ISSUE TITLE
Hello, how do I compile an exe installation package under ubuntu? Or how do I get an installation package for a self-compiled exe?

### ISSUE THREAD

**Issue by xuquankun** [reorproject/reor#292]

**Comment by xuquankun** [comment]
I did this, but I ran into a module failure, such as ‘’eslint‘’、‘’vectordb‘’, if I ignore these problems, the final compiled exe installation package will not be executed.
![image](https://github.com/reorproject/reor/assets/37311981/5fbe5a89-20d2-42e0-b148-40445ba1c3d1)

**Comment by weilirs** [comment]
Did you pull the latest commit? `lancedb/vectordb-win32-x64-msvc` should be an optional package now.

**Comment by xuquankun** [comment]
> Did you pull the latest commit? `lancedb/vectordb-win32-x64-msvc` should be an optional package now.
Yes, I pulled the latest commit, and after compiling it still reported the same error, what system environment did you compile in?

**Comment by weilirs** [comment]
I am not using Ubuntu, sorry I can't help you with that...

**Comment by samlhuillier** [comment]
In my experience, given the complexity of the packages we use for running local models (onnx and ollama), you can't really build for a different OS than the OS you are building on - it tends to lead to a broken build...
