### ISSUE TITLE
Error invoking remtoe method 'search-with-reranking' when clicking on "Rerank results"

### ISSUE THREAD

**Issue by liangdong415** [reorproject/reor#293]
**Describe the bug**
Error invoking remtoe method 'search-with-reranking' when clicking on "Rerank results"

**To Reproduce**
1. Go to 'Files -> Related Notes'
2. Click on 'Rerank results'

**Expected behavior**

**Screenshots**
![image](https://github.com/reorproject/reor/assets/6811528/09798ccc-7cf3-46b4-8c71-96f161a2fdef)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version  0.2.10

**Additional context**

**Comment by samlhuillier** [comment]
Thanks for reporting @liangdong415 we have disabled this feature for now
