### ISSUE TITLE
FR: change the destination of the vault

### ISSUE THREAD

**Issue by deven367** [reorproject/reor#30]
As of now, there is no way to update the destination of the vault. Can someone please guide through this process? TIA!

**Comment by samlhuillier** [comment]
As a patch, you can delete electron store config and restart the app. Though a PR merge is imminent: #28 just need to make sure it doesn't break anything seeing as it's quite big. To clear the store do the following:

Windows
Locate the User Data Directory: For a Windows application, the Electron store data is usually located in C:\Users\[Your User Name]\AppData\Roaming\[Your App Name].
Delete the Store File: Find the file associated with the Electron store (often named something like config.json or similar) and delete it.

macOS
Locate the User Data Directory: On macOS, the path is typically ~/Library/Application Support/[Your App Name].
Delete the Store File: Find the Electron store file and delete it.

Linux
Locate the User Data Directory: For Linux, the path is usually ~/.config/[Your App Name].
Delete the Store File: Locate and delete the Electron store file.

**Comment by SamKry** [comment]
Under MAC, i was able to change the Vault destination in the `config.json` file. It was located in:

`/Users/[USERNAME]/Library/Application Support/Reor/config.json`

Just replace the old path with your new one. 

However, it would be nice if there is a corresponding setting in the graphical user interface to change the Vault directory. :)

**Comment by samlhuillier** [comment]
This is now available!!! In the new release: https://github.com/reorproject/reor/releases/tag/v0.1.47
