### ISSUE TITLE
Close Chatbot chats or chat history won't delete on Windows 11 Pro.

### ISSUE THREAD

**Issue by AJ2088RD** [reorproject/reor#323]
**Describe the bug**

When I click on Delete Chat the chat or chat history doesn't delete and stays there. I downloaded it for windows from reorproject.Org

**To Reproduce**

1. Go to 'Close Chatbot'
2. Right Click on a chat so that the option to 'Delete Chat' will appear.
3. Then left click on the 'Delete Chat' option and then chat or chat history doesn't delete.

**Expected behavior**

I expect when I click delete chat for the chat or chat history to delete.

**Screenshots**

![image](https://github.com/user-attachments/assets/55685917-4ae9-4e5f-b2ed-facd348df79a)

**Desktop (please complete the following information):**

 - OS: [ Microsoft Windows 11 Pro]
- Hardware: [Intel(R) 12TH Gen Alder Lake N100 800MHz Processor, 8.00 GB RAM, Intel UHD Graphics GPU]
 - Version [Windows 11 Pro Version 23H2]

**Additional context**
It is a Mini PC called GMKtec NucBox G3.

**Comment by AJ2088RD** [comment]
i pasted the commands on CMD but nothing happens

**Comment by AJ2088RD** [comment]
can you give me step by step instructions?

**Comment by weilirs** [comment]
That was an AI response and I think we need to fix it manually. Thank you for pointing out the bug!

**Comment by razorback21** [comment]
Inside the file electron\main\electron-utils\ipcHandlers.ts

replaced the line 

`const filteredChatHistories = allChatHistories.filter((item) => item.id !== chatID);`

`with const filteredChatHistories = allChatHistories.filter((item) => item.id !== chatID.id); `

**Comment by samlhuillier** [comment]
Great spot @razorback21! Would be great if you could throw those changes into a PR so that we can get this fix out to users :)

**Comment by razorback21** [comment]
@samlhuillier. I have submiited the [PR](https://github.com/reorproject/reor/pull/332) for review.
