### ISSUE TITLE
Redesign Chat UI

### ISSUE THREAD

**Issue by milaiwi** [reorproject/reor#341]
The current Chat UI is plain and does not match the UI for everything else. Things to do:

- Make chat colors contrast well
- Add padding on chat information
- Change color of text to match the text of the editor

**Comment by CubicalBatch** [comment]
Another thing to consider (at least on Linux)

When the LLM gives me a long line in backtick quotes, if the line is longer than the width of my window it will squash the left column (chat list / file list), with no way to access it unless I expand the width of my window

![Unsaved Image 1](https://github.com/user-attachments/assets/94fd175f-a36b-4726-b5fe-d8d59056c69e)

Thanks!

**Comment by milaiwi** [comment]
Yeah I'm almost done with this. Just need to make some small changes like:

- Stop streaming response when chat changes
- Stop loading response when chat changes

Right now if the chat is streaming a response and you change to a file or new chat it will continue writing.
