### ISSUE TITLE
Move context menu to frontend instead of backend

### ISSUE THREAD

**Issue by milaiwi** [reorproject/reor#358]
Should move the Context Menu to the frontend instead of backend for multiple reasons:

- Ability to add animation on dragging (tabs, files, chats)
- Ability to add a custom UI that is consistent on different platforms
- More dynamic

Let me know what y'all think!

**Comment by joseplayero** [comment]
yes agree this would be good

**Comment by milaiwi** [comment]
@joseplayero Yeah, I've already implemented it. Just need to add a fix where it does not overflow outside of its container and instead opens in a different direction.
