### ISSUE TITLE
Fix newline issue in markdown editor

### ISSUE THREAD

**Issue by joseplayero** [reorproject/reor#362]
### Problem

When a user types newlines into the editor, closes the file and re-opens it, those newlines disappear. Only holding shift while pressing enter preserves the newlines and its because the markdown file gets saved with backslashes \ where the newlines are.

### Solution
Fix the issue without needing backslahses and ideally without conditional logic manually parsing particular characters but with changes to the extension settings/config - like [tiptap markdown](https://github.com/aguingand/tiptap-markdown). 

We should look to basically have the same behaviour as Obsidian which saves newlines to markdown without backslashes and then opens those files with newlines correctly placed in the editor.

**Comment by Mubashirshariq** [comment]
@joseplayero can i get this assigned,if nobody is working on it!

**Comment by milaiwi** [comment]
@joseplayero Can you assign this to @Mubashirshariq. I'm currently busy with other stuff right now.

**Comment by joseplayero** [comment]
Absolutely you're assigned @Mubashirshariq !

**Comment by Mubashirshariq** [comment]
@joseplayero  i was working on this and i debugged it got the follwoing results the backslash right next to first heading is not getting converting to backslash all the others are getting converted
markdown:
`
  # firstone\
\
\
\
\
\
sgde
`

editor: 
` firstone\





sgde
`

and in html all the `\` are getting converted to <br> tag but the first one is rendered as <h1>firstone\<h1>

**Comment by Mubashirshariq** [comment]
For "Enter " to work same as "Shift + enter "  i have added that

**Comment by joseplayero** [comment]
Yes please go ahead @jkcs :)

**Comment by amochuko** [comment]
Am available to give it a go.

**Comment by govindup63** [comment]
if this issue isn't resolved can i get assigned to it coz I made an attempt earlier

**Comment by joseplayero** [comment]
please both try it @govindup63 @amochuko

**Comment by joseplayero** [comment]
Unassigned @amochuko & @govindup63 as looks like no progress.

@milaiwi now assigned!

**Comment by itsdheerajdp** [comment]
/attempt #362
@joseplayero I don't see any upates in the PR. If this issue is open for anyone rn. i'll love to work on it
