### ISSUE TITLE
New note creating issue

### ISSUE THREAD

**Issue by pachieh** [reorproject/reor#364]
When creating a new note in the root directory using the icon on the left menu bar, it is creating a new directory, sub directory, and then the note.  The two directories it creates take the name of the note you type in as well. Noticed this today after trying to name a note. Very odd.

macOS Sonoma 14.6.1
Reor 0.2.19

**Comment by joseplayero** [comment]
Could you explain a bit more how to reproduce this/do a little screen record to show what happened? I tried replicating this and i could not

**Comment by pachieh** [comment]
When I hit the create new note icon and type in a name, it would create two folders and then the note. 

And like taking your car to a mechanic, I tried to do screenshots/recording and it stopped doing it.

**Comment by pachieh** [comment]
<img width="1473" alt="Screenshot 2024-08-21 at 14 00 15" src="https://github.com/user-attachments/assets/d660f7df-21bf-4b94-b786-42c4903b8127">

See attached. It's hard to do a recording, will try again because it doesn't happen all the time.

**Comment by milaiwi** [comment]
Weird. I was able to reproduce it and I think this is a simple fix. I'll make a PR soon. 

Steps to reproduce:
- Click 'New Note' Icon
- Put in name "Design Thinking (Rauch/Tackett)"

Bug:
- Creates a folder and a folder with incorrect name

**Comment by milaiwi** [comment]
Okay, this error happens on the creation of the file. Users should not be able to have any form of slashes in their title since slashes represent directories and files in paths. To fix this, we need to check `getInvalidCharacterInFileName` on the creation or a note or directory
