### ISSUE TITLE
Auto scroll in chat & writing assistant

### ISSUE THREAD

**Issue by joseplayero** [reorproject/reor#376]
### Problem
When the LLM is generating text in chat and the writing assistant, the text generated goes below the component because the component does not scroll for the user to the bottom where the LLM's latest generated text is.

### Solution
Autoscroll in chat and writing assistant. This should auto scroll to the bottom of the LLM's generated text but if the user scrolls themselves (against the auto scroll) then the user's scroll overrides the auto scroll. If the user overrides the auto scroll, the auto scroll should not be re-activated until the next time the LLM is generating (i.e. the next message is sent).

As always, code should be clean and easily understandable :)

**Comment by DevGajjar28** [comment]
Hi @joseplayero 

I'm having an issue while installing Reor for contribution. I followed the [contributing guide](https://www.reorproject.org/docs/documentation/contributing), but I encountered a problem when running the npm run dev command. The following error message appears:

exec error: Error: Command failed: "D:\open-source\Bounty\New folder\reor\binaries\win32\ollama-windows-amd64.exe" serve
'"D:\open-source\Bounty\New folder\reor\binaries\win32\ollama-windows-amd64.exe"' is not recognized as an internal or external command,

The contributing guide does not mention anything about this issue. Could you please provide some guidance on how to resolve this?

**Comment by itsdheerajdp** [comment]
@joseplayero can i get it assigned so that i'll start working on it

**Comment by joseplayero** [comment]
i will assign @DevGajjar28 for now as he was first to submit attempt

**Comment by samlhuillier** [comment]
ive re-assigned to @Vayras for now. please attempt and submit a PR asap and ill review

**Comment by itsdheerajdp** [comment]
@samlhuillier I know how to deal with it. Can I give it a try ?

**Comment by monyishh** [comment]
can i work upon it?

**Comment by joseplayero** [comment]
pls wait to implement actually. this issue is blocked by refactor work this week. will close issue temporarily

**Comment by raphaelbernhart** [comment]
@joseplayero Is this still needed? :)
