### ISSUE TITLE
AI based personal notes app

### ISSUE THREAD

**Issue by heonmin** [reorproject/reor#38]
https://github.com/reorproject/reor

**Comment by heonmin** [comment]
Olympic peninsula
Gorilla Rock @Ruby beach

https://www.whatcomtalk.com/2023/03/05/popular-ruby-beach-on-the-washington-coast-has-been-given-a-new-parking-lot-and-improved-accessibility/olympic-peninsula-ruby-beach-gorilla-rock/

**Comment by samlhuillier** [comment]
What?
