### ISSUE TITLE
Add send button to chat window & dropdown to choose LLM

### ISSUE THREAD

**Issue by joseplayero** [reorproject/reor#381]
### Problem
In the new chat window users cannot choose which LLM to send a message to nor is there a button to send a message to the LLM

### Solution
1. Dropdown to choose an LLm using get llm configs function
2. Add a send button (with a little arrow icon) where the 'context selector' button is right now and move the context selector button to the middle between the new llm dropdown and the new send button

**Comment by itsdheerajdp** [comment]
@joseplayero can i get it assigned so that i'll start working on it

**Comment by itsdheerajdp** [comment]
@joseplayero is llmConfigsFromStore is iterable ?? currently we are returning any llms from get-llm-configs function ??

**Comment by itsdheerajdp** [comment]
@joseplayero ig i forgot to claim the bounty ? as the changes got merged but didn't get the tip
