### ISSUE TITLE
AI Assistant Options Partially Hidden or Not Visible While Scrolling down the page and Selecting Text

### ISSUE THREAD

**Issue by itsdheerajdp** [reorproject/reor#402]
**Is your feature request related to a problem? Please describe.**
While working on a project, I encountered an issue where the AI assistant options panel behaves unexpectedly when scrolling through a text file and selecting its content. The options panel either becomes partially visible (only half is shown) or disappears entirely from view depending on the scroll position of the page.

**Steps to Reproduce**
1. Open a text file in the project that has enough content to scroll.
2. Scroll down and select a portion of the text.
3. Observe the behavior of the AI assistant options panel.

**Describe the solution you'd like**
I can work on adjusting the position of the Ai Assistant options to make it work perfectly.

**Additional context**
The Problem is seen Below in the Video.

[screen-capture.webm](https://github.com/user-attachments/assets/b71209ce-e4c4-4641-b1a3-c8ead8679a7f)

**Comment by itsdheerajdp** [comment]
@joseplayero If this is indeed an issue, I would be delighted to work on resolving it.

**Comment by weilirs** [comment]
I double-checked it and I experienced the same bug, please go for it if you want to fix it.

**Comment by joseplayero** [comment]
good find @itsdheerajdp. please modify writing assistant to use this for wrapping the writing assistant https://ui.shadcn.com/docs/components/popover

make sure you write high quality react code. tips will be come if you do
