### ISSUE TITLE
Chat not responding because of context being too long

### ISSUE THREAD

**Issue by anaclumos** [reorproject/reor#41]
<img width="875" alt="image" src="https://github.com/reorproject/reor/assets/31657298/5f17eb2a-b653-4b14-a65b-5aa21f2d717a">

<img width="548" alt="image" src="https://github.com/reorproject/reor/assets/31657298/a2696c11-f5f0-46e3-b197-9466486f4558">

**Comment by chasemcdo** [comment]
Getting the same error

**Comment by cunla** [comment]
Just adding the error text:
> Uncaught (in promise) Error: Error invoking remote method 'augment-prompt-with-rag': Error: The provided information is too long to process in a single prompt. Please shorten the query or provide fewer details

**Comment by DiogoNeves** [comment]
I'm going to start using Reor! and would love to contribute 😄 
What's the desired behaviour here?

Is the problem that the user prompt + retrieved documents are too large?
Would calculating the tokens upfront and truncate the retrieved chunks to stay within the max tokens?

@chasemcdo can you see what was the complete prompt being sent to the model?

**Comment by chasemcdo** [comment]
@DiogoNeves I think this may have been fixed in #44 but i haven’t confirmed yet

**Comment by samlhuillier** [comment]
Yes thanks to @ryanmcdonough this should be fixed! New release on its way. Once it's out, could you folks confirm the error has gone?

**Comment by cunla** [comment]
Sure

**Comment by samlhuillier** [comment]
Available now: https://github.com/reorproject/reor/releases/tag/v0.1.45

**Comment by cunla** [comment]
Solved in the new version. Thx!
