### ISSUE TITLE
[ Enhancement ] : Background around the Input Field of Chat Page

### ISSUE THREAD

**Issue by itsdheerajdp** [reorproject/reor#416]
**Is your feature request related to a problem? Please describe.**
The Background around the input field of the chat page is making UI inconsistent as shown in below image 

![reor_issue](https://github.com/user-attachments/assets/306b4b81-fe85-4349-af4a-f9eb0bd866c0)

![input_field](https://github.com/user-attachments/assets/59e94096-56b1-4399-ac10-7e1cd3baeebe)

**Describe the solution you'd like**
We can try to have this background only inside the input field and try to avoid it around the field

**Additional context**

**Comment by joseplayero** [comment]
this being fixed in current open pr
