### ISSUE TITLE
Minor issue with fill for related notes

### ISSUE THREAD

**Issue by chuyouchia** [reorproject/reor#42]
Hey @samlhuillier fantastic project, I was about to make something like this until I saw your HN post!

Minor bugfix - the fill on the related notes minimizer is not working, which is slightly confusing.

I think I have the working fix for it, tested locally. It is just some fairly simple state management. I would put up a PR, but I think it isn't allowing me to do that as a non-contributor.

<img width="542" alt="image" src="https://github.com/reorproject/reor/assets/58682208/1f056207-483f-4aa3-81f0-50a458906c68">

**Comment by samlhuillier** [comment]
Thank you for doing this! I've added you as a contributor so feel free to open a PR now :)
