### ISSUE TITLE
Redundant "agent" displayed when selecting options in chatbot

### ISSUE THREAD

**Issue by itsdheerajdp** [reorproject/reor#424]
**Description**
When selecting options in the start chat page of the AI chatbot, there is a redundancy in the message displayed. The word "agent" is shown twice in two of the options: "Research Agent" and "Daily Note Agent." The same issue does not occur when selecting the "Default" option.

**Steps to Reproduce:**
1. Go to the start chat page of the AI chatbot.
2. Click on the "Default" option.
     - Observed message: "Using the Daily Note Agent agent. How can I help you?"
3. Click on the "Research Agent" option.
     - Observed message: "Using the Research Agent agent. How can I help you?"
4. Click on the "Daily Note Agent" option.
    - Observed message: "Using the Daily Note Agent agent. How can I help you?"

**Expected Behavior**
The message should only display the word "agent" once, e.g., "Using the Research Agent. How can I help you?" or "Using the Daily Note Agent. How can I help you?"

**Actual Behavior**
The word "agent" appears twice, causing a repetitive phrase:
- "Using the Research Agent agent."
- "Using the Daily Note Agent agent."

**Screenshots**

![default_reor](https://github.com/user-attachments/assets/e225e418-d1b1-41ff-9626-85a62411953f)

![research_agent_reor](https://github.com/user-attachments/assets/4c01d4ae-41ed-4f97-abc9-abb7c1b3d8cf)

![daily_note_agent_reor](https://github.com/user-attachments/assets/e2789e07-181d-48ea-b25e-09575e00bc24)

**Comment by samlhuillier** [comment]
This is just current progress. Will be fixed
