### ISSUE TITLE
Writing assistant checkbox for feeding current editor contents to llm

### ISSUE THREAD

**Issue by joseplayero** [reorproject/reor#441]
the writing assistant should have a little checkbox (that is toggled on by default) to allow user to automatically feed in context from the current editor contents without needing to highlight the whole file.

- this parameter should be stored to the electron-store so that user does not need to retoggle it each time

(do not attempt issue unless assigned to it)

**Comment by RohanMishra315** [comment]
Hey @joseplayero Should I do it ?

**Comment by hunxjunedo** [comment]
@joseplayero what's the status of this issue ? Is this up for grabs or already assigned.

**Comment by weilirs** [comment]
> the writing assistant should have a little checkbox (that is toggled on by default) to allow user to automatically feed in context from the current editor contents without needing to highlight the whole file.
> 
> * this parameter should be stored to the electron-store so that user does not need to retoggle it each time
> 
> (do not attempt issue unless assigned to it)

So, should the checkbox be placed in the settings?
To trigger this functionality, do we use a keyboard shortcut?

**Comment by joseplayero** [comment]
for now imo this checkbox should be a small switch inside the writing assistant component

**Comment by weilirs** [comment]
And use a shortcut to trigger this functionality?
