### ISSUE TITLE
writing assistant follow up

### ISSUE THREAD

**Issue by joseplayero** [reorproject/reor#442]
### problem
- the writing assistant should allow follow ups for user to steer llm's generation

### solution
- this should be designed nicely and intuitively so that it is clear to user that they can follow up on previous message from writing assistant
- the user should be able to see previous follow ups, not just latest follow up

(do not attempt issue unless assigned to it)

**Comment by RohanMishra315** [comment]
hey @joseplayero Should I work on this ! It's quite easy to implement !
