### ISSUE TITLE
if no LLMs attached, there should be a button to add LLMs in chat

### ISSUE THREAD

**Issue by joseplayero** [reorproject/reor#445]
### problem

if the user has not added any llm to reor this is an empty dropdown in chat:
<img width="204" alt="Screenshot 2024-10-11 at 06 05 31" src="https://github.com/user-attachments/assets/2f0c20ca-4a76-416a-950a-a7f6fd5cba96">

### solution
when there are no attached llms, there should be a button instead of the select dropdown to allow user to 'attach llm'. this button should use the commonmodals context to open settings on the llms page. 

- this change will require an additional modification to make the llm tab within settings the default one that opens in settings
- it will also require a very small refresh icon next to or below the 'attach llm' button and the dropdown which refreshes the llms config by pulling from electron store

**Comment by Mubashirshariq** [comment]
@joseplayero can I work on this

**Comment by joseplayero** [comment]
issue has been assigned @Bhavyajain21

**Comment by Bhavyajain21** [comment]
Thanks for assigning! @joseplayero

**Comment by Mubashirshariq** [comment]
@joseplayero i commented first ideally is should be assigned

**Comment by Bhavyajain21** [comment]
> @joseplayero i commented first ideally it should be assigned to me

Hey @Mubashirshariq , please comment with "/attempt" as per algora contributing guidelines.

**Comment by Mubashirshariq** [comment]
> > @joseplayero i commented first ideally it should be assigned to me
> 
> Hey @Mubashirshariq , please comment with "/attempt" as per algora contributing guidelines.

Dude I know ,but I think in this repo they assign first after that you can attempt

**Comment by joseplayero** [comment]
that is incorrect @Mubashirshariq. See https://www.reorproject.org/docs/documentation/contributing#bounties

**Comment by Mubashirshariq** [comment]
> that is incorrect @Mubashirshariq. See https://www.reorproject.org/docs/documentation/contributing#bounties
@Bhavyajain21 can work on this not an issue for me ,I can attempt other issues,but I can see this line in the above link

`To avoid duplicate work, please wait until you are assigned to an issue before starting work `

That is why I asked you  for assign first before writing /attempt, anyways I will look for other issues
