### ISSUE TITLE
allow for deletion of ollama models

### ISSUE THREAD

**Issue by joseplayero** [reorproject/reor#452]
### problem

can't right now delete ollama models

### solution

- use [ollama](https://www.npmjs.com/package/ollama) npm library and call .delete method to delete model
- create ipc handler which calls this method
- forward ipc handler via preload to renderer process
- in default llm dropdown in settings have a small delete icon next to ollama/local llms that calls the delete preload function

**Comment by joseplayero** [comment]
@Bhavyajain21

**Comment by Bhavyajain21** [comment]
Please assign @joseplayero

**Comment by joseplayero** [comment]
<img width="652" alt="Screenshot 2024-10-15 at 10 44 21" src="https://github.com/user-attachments/assets/91070d48-1af5-446f-b8aa-fa09c83ba34c">
in settings next to only ollama models there should be a small bin icon to click and trigger the delete call through the preload. so in the image example above only llama3.2 should have a delete icon next to it
