### ISSUE TITLE
Container build

### ISSUE THREAD

**Issue by rpdelaney** [reorproject/reor#46]
Would you accept a pull request with a `Containerfile` for running the app with podman or docker?

**Comment by samlhuillier** [comment]
Absolutely, that'd be great to see!

**Comment by rpdelaney** [comment]
Can I ask why we `.gitignore` the `package-lock.json` file? My understanding is that having a lock file is necessary to ensure the builds are reproducible.

**Comment by samlhuillier** [comment]
Yes of course. My apologies for this - so much time solo deving this project has led to things like this slipping through! Could you add the ```package-lock.json``` as part of a PR?

**Comment by samlhuillier** [comment]
Any update on this @rpdelaney ?

**Comment by rpdelaney** [comment]
Nope. Are you blocked on something or just excited? :)

**Comment by samlhuillier** [comment]
Just excited!

**Comment by rpdelaney** [comment]
I'm a bit confounded by needing to install runtime dependencies for Electron even when using their base images. Perhaps this is my inexperience with the ecosystem showing. [Here](https://github.com/reorproject/reor/compare/main...rpdelaney:reor:containerize?expand=1)'s where I am now:

```console
$ podman run --rm localhost/reor:latest

> reor-project@0.1.45 dev
> vite


  VITE v4.5.2  ready in 368 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
vite v4.5.2 building for development...

watching for file changes...
vite v4.5.2 building for development...

watching for file changes...

build started...

build started...
transforming...
transforming...
✓ 1 modules transformed.
rendering chunks...
computing gzip size...
dist-electron/preload/index.js  20.92 kB │ gzip: 6.12 kB │ map: 11.96 kB
built in 141ms.
✓ 108 modules transformed.
rendering chunks...
computing gzip size...
dist-electron/main/index.js  316.34 kB │ gzip: 61.50 kB │ map: 641.20 kB
built in 720ms.
/usr/src/app/node_modules/electron/dist/electron: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

It has been many times I added things to lines 6-16 and I am tired. Once that is done next step would be to optimize the final image size. It's my gift to you or anyone else who might want to take it from there before I get a second wind 😓
