### ISSUE TITLE
[Regression-0.2.29] Selection dialogs are hidden in Welcome Screen

### ISSUE THREAD

**Issue by LFd3v** [reorproject/reor#484]
**Describe the bug**
Selection dialogs are hidden in Welcome Screen

**To Reproduce**
1. Download and run Reor on a new system (i.e. missing or empty `~/.config/Reor`)
2. Try to use Embedding Model or LLM options

**Expected behavior**
The pop-up dialog and drop-downs menu should be visible to the user in the Welcome screen.

**Screenshots**
Please see below.

**Desktop (please complete the following information):**
 - OS: ArchLinux/Garuda GNOME Wayland
 - Hardware: i5 13th Gen 16GB + NVidia 3050 6GB
 - Version 0.2.29 AppImage

**Additional context**
Tested with v0.2.26 AppImage and it worked fine.

![Screenshot From 2024-11-13 13-26-24](https://github.com/user-attachments/assets/07d616b6-a04e-48bf-8aef-fe8799cc94ca)

**Comment by samlhuillier** [comment]
Thanks for letting us know this is now fixed in the new release :)
