### ISSUE TITLE
Korean input is not available in 'Note name' and 'Directory name'

### ISSUE THREAD

**Issue by kanghohyeong** [reorproject/reor#60]
When entering Korean in 'Note name' for create new note or 'Directory name' for create new directroy, it does not proceed with the error phrase below.
`Note name can only contain letters, numbers, underscores, hyphens, and slashes.`

**Comment by samlhuillier** [comment]
Yes this would be a straightforward fix in ```newnote.tsx``` and ```newdirectory.tsx```. I can do this or would you like to work on it and open a PR?

**Comment by kanghohyeong** [comment]
Sure, I'll open a PR and take care of it. I think this solution can work.
https://stackoverflow.com/a/54879743

**Comment by samlhuillier** [comment]
Great yes that looks relevant. Perhaps, included in this PR we could drop the stringent requirements against most special characters and stick to exactly the same requirements operating systems set.
<img width="505" alt="Screenshot 2024-02-21 at 15 54 07" src="https://github.com/reorproject/reor/assets/17236551/b96e55bd-56e8-41e1-88d5-ee9fef6fdd1b">

**Comment by kanghohyeong** [comment]
Good. Here is a references to the file name rule. https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words

**Comment by kanghohyeong** [comment]
@samlhuillier I try `npm run dev` but electron application does not launch. After build, process is just terminated. Is there any more preparation for development?
```sh
~/Project/reor (main) » npm run dev                                                                                                                                   hohyeongkang@Hobro-MacAir

> reor-project@0.1.49 dev
> vite


  VITE v4.5.2  ready in 242 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
vite v4.5.2 building for development...

watching for file changes...
vite v4.5.2 building for development...

watching for file changes...

build started...

build started... (x2)
✓ 1 modules transformed.
dist-electron/preload/index.js  22.48 kB │ gzip: 6.15 kB │ map: 12.91 kB
built in 98ms.
✓ 110 modules transformed.
dist-electron/main/index.js  325.64 kB │ gzip: 62.91 kB │ map: 655.54 kB
built in 579ms.
```

**Comment by samlhuillier** [comment]
@kanghohyeong I suspect this is happening because you have Reor open so it can't open a dev build...

**Comment by kanghohyeong** [comment]
@samlhuillier When referring to the [following](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words) , my conclusion is not to manage the 'permitted character set', but to manage the 'prohibited character set' like this `/[^/\\?%*:|"<>.;=\s]/`

**Comment by kanghohyeong** [comment]
maybe prohibit `\ " ' * ; - ? [ ] ( ) ~ ! $ { } &lt > # @ & | space tab newline` these character can be widely support major os (Windows, Mac, Linux )

**Comment by samlhuillier** [comment]
@kanghohyeong Thank you for opening a PR! I've added some comments under your PR.

**Comment by samlhuillier** [comment]
@kanghohyeong thank you for your work! This is now released in the [latest version](https://github.com/reorproject/reor/releases/tag/v0.1.52)
