### ISSUE TITLE
Can't fetch Embedding Model because of Proxy

### ISSUE THREAD

**Issue by ITZRei** [reorproject/reor#69]
It's not possible to fetch the Embedding Model because of the Proxy/Firewall. Where to put the Model manualy? Or use the configured Proxy.

**Comment by samlhuillier** [comment]
Yes. I am implementing a workaround now. What do you mean by "use the configured Proxy"?

**Comment by ITZRei** [comment]
"use the configured proxy" -> normaly there is a proxy configuration either in Windows or Linux. This is set in the environment variables.

**Comment by samlhuillier** [comment]
Now pushed out a fix for the proxy issues which should fix this error message entirely, download the model automatically and get rid of this error: https://github.com/reorproject/reor/releases/tag/v0.1.50

**Comment by ITZRei** [comment]
Hi, it's works like a charm ;) Thanks
