### ISSUE TITLE
Illegal instruction while running Reor 0.1.48.AppImage on Ubuntu 22.04

### ISSUE THREAD

**Issue by leemgs** [reorproject/reor#73]
I downloaded Reor 0.1.48.AppImage  to run models on Ubuntu 22.04
It's weird. I met the below error. 

```
invain@u2204:~/Download$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
invain@u2204:~/Download$ chmod 755 ./Reor_0.1.48.AppImage 
invain@u2204:~/다운로드$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

invain@u2204:~/Download$ ./Reor_0.1.48.AppImage 
Illegal instruction (core dumped)

invain@u2204:~/Download$ ./Reor_0.1.48.AppImage 
Illegal instruction (core dumped)

```

**Comment by samlhuillier** [comment]
Thanks for raising this!
Which architecture do you use? You can find out with:
```
uname -m
```

**Comment by leemgs** [comment]
Here  is  the architecture information that I ran the Reo.AppImage on my Ubuntu 22.04.

```
invain@u2204:~$ uname -a
Linux u2204 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
invain@u2204:~$ uname -m
x86_64
invain@u2204:~$
```

**Comment by leemgs** [comment]
I confirmed that this issue was resolved in **Reor 1.5.1** version. Thank you.

* Screenshot:

**Comment by samlhuillier** [comment]
Great I will close this issue then! Please feel free to reopen it if you see the issue again.

**Comment by yourdesigncoza** [comment]
I see this "issue" was closed however I'm getting the  same error : 

./Reor_0.2.31.AppImage
Illegal instruction (core dumped)
