### ISSUE TITLE
CPU usage spiking to 100% when typing notes

### ISSUE THREAD

**Issue by ekianjo** [reorproject/reor#74]
I guess Reor uses some kind of real-time system to analyze the notes and transform them into word embeddings. It works well but I noticed that when typing, the CPU usage will jump to 100% (on Linux at least), using all cores at the same time, making the text input freeze sometimes. 

Would there be a way to ensure that Reor does not use all CPU resources available by default, so that it does not slow down the reactivity of the system?

**Comment by samlhuillier** [comment]
Thank you for opening this. 

Reor works by periodically writing the contents of the editor to the filesystem and at the same time embedding those contents into the vector database. Perhaps we could think about implementing a customisable indexing period to get rid of this slowness. @ekianjo what cpu/ram/gpu do you have?

@andreofthecape this is strange. Have you tried with the [latest release](https://github.com/reorproject/reor/releases/tag/v0.1.50) and experience the same thing?

**Comment by callado4** [comment]
FWIW, I'm experiencing this on 0.1.51 using a Mac.

**Comment by samlhuillier** [comment]
We have made changes to fix this which will be released later on today.

**Comment by callado4** [comment]
So far so good for me @samlhuillier, I really appreciate the fix.  Now I'm not getting some annoying delays while typing which tends to affect my mental flow.  

I would suggest to wait for @ekianjo to give some feedback just because the original issue was for Linux and I wouldn't want it to be closed without confirming that use case (and I'm on a Mac)

**Comment by samlhuillier** [comment]
@callado4 Amazing! Glad to be of service to your mental flow! Would love to know too if you have any other feedback/new features you'd want added...

**Comment by ekianjo** [comment]
@samlhuillier  let me give it a spin, will let you know how it feels

**Comment by ekianjo** [comment]
@samlhuillier  looks to be better in the latest version 0.154, so you can close this ticket :-)

**Comment by samlhuillier** [comment]
Great!
