### ISSUE TITLE
 failed to initialization all embedding model.

### ISSUE THREAD

**Issue by pca15hj** [reorproject/reor#75]
Indexing error: Error: Resource initialization failed: Error: Pipeline initialization failed for repo 'Xenova/bge-small-en-v1.5': TypeError: fetch failed.

it failed to initialization all embedding model.

**Comment by samlhuillier** [comment]
I am working on a fix for this now. This issue comes from difficulties in downloading the embedding model automatically for you from huggingface. It is related I think to issues with proxy/vpn causing the download to fail. Could you tell me if you have any of these? Also if you are in a country that perhaps blocks access to certain websites?

**Comment by pca15hj** [comment]
Yes, i do use vpn. However, i did download the rero on my office laptop, it showed another issue which i forget...
i'll try download again without vpn.

**Comment by pca15hj** [comment]
well, it doesn't work.

**Comment by pca15hj** [comment]
China

**Comment by samlhuillier** [comment]
Gotcha. I am working on allowing for manual downloads right now. Are you aware of any issues with automatic huggingface downloads using transformers library that affect users in china?

**Comment by pca15hj** [comment]
no, it seems work to me.

**Comment by samlhuillier** [comment]
I have just released a new version that allows you to download an embedding model from huggingface and attach it yourself. The new release is [here](https://github.com/reorproject/reor/releases/tag/v0.1.49) and a guide is [here](https://www.reorproject.org/docs/documentation/embedding).

I am also working on a fix to get around the proxy issues as we speak :)

**Comment by samlhuillier** [comment]
Now pushed out a fix for the proxy issues which should fix this error message entirely, download the model automatically and get rid of this error: https://github.com/reorproject/reor/releases/tag/v0.1.50
