### ISSUE TITLE
BUG: Notes overwriting each others

### ISSUE THREAD

**Issue by ekianjo** [reorproject/reor#77]
I am not sure if this is already known or not, but I have come across this problem where Reor overwrites the content of one note with the content of another note. It does not happen in very specific conditions, so I don't have any way for you to replicate the issue, but I am 100% sure this is happening since I lost a fairly long note and its content (only the content, not the markdown file title) was replaced with the exact content from another smaller note. 

Might be worth some investigation, and this is a killer-issue for anyone considering a serious usage of Reor.

**Comment by samlhuillier** [comment]
Thank you for opening this and apologies for the delay in responding!

Could you point me towards how I could go about reproducing this? I've been using Reor heavily for the past months and haven't noticed this so would be keen to see how perhaps your workflow differs and causes this issue.

**Comment by enzy** [comment]
I have noticed that every viewed file (did not save it manually) got somehow overwritten a bit - based on the timestamps. When comparing file sizes they also differ. Contents differ - mainly in the markdown formatting.

**Comment by samlhuillier** [comment]
@enzy yes unfortunately right now that is the case. A big project that I'm aiming to get out in the next week or two is to change text editor and use something like tiptap. This would help achieve lots of things including preventing unnecessary formatting provided by the current solution. Sorry about this.

**Comment by rgmerck** [comment]
@samlhuillier this issue is still happening in Reor 0.158 (just saw it happening in front of my eyes as I was switching between notes, and one of them got overwritten with the contents of the previous one I selected). This is a major issue.

**Comment by samlhuillier** [comment]
@rgmerck I've just merged and [released](https://github.com/reorproject/reor/releases/tag/v0.1.59) a version that should fix this. I'd be grateful if you could try it and let me know if you notice the issue :)

**Comment by rgmerck** [comment]
@samlhuillier did a  very quick and dirty check this morning and it looks like the issue does not occur anymore! I think you can close this for now. If I notice the behavior happening again i will open a new ticket.
