### ISSUE TITLE
cannot use GPU with win11

### ISSUE THREAD

**Issue by leeyaunlong** [reorproject/reor#79]
Use the "openchat-3.5-7b" model with win11, just used cpu. the reor cannot use GPU.
I can use the same model (GPU) with JAN.AI appliaction.

**Comment by Nasnl** [comment]
Same here, while using Gemma 7B locally.

**Comment by drgutman** [comment]
+1 
It would be useful to have an option available to switch between the GPU and CPU modes.

**Comment by drgutman** [comment]
@samlhuillier - Yes, cuda_12.3.2_546.12_windows, GeForce RTX 3060.

**Comment by leeyaunlong** [comment]
> Working on this now. @drgutman @Nasnl @leeyaunlong Just for my info, do you guys have cuda installed? Which gpu do each of you use?

CUDA Version: 12.1 , win11, intel 11gen i9

PS: I can use the JAN.AI with 7B model.  current I use JAN.AI's api with Reor.

**Comment by samlhuillier** [comment]
@drgutman @Nasnl @leeyaunlong GPU support via CUDA is now out in the [latest version](https://github.com/reorproject/reor/releases/tag/v0.1.51)!

You'll have to turn it on in Settings -> Hardware -> Toggle GPU and CUDA on

(There is also Vulkan support for AMD GPUs.)

**Comment by leeyaunlong** [comment]
thanks, it's work well now.

**Comment by leeyaunlong** [comment]
thanks, it's work well now.

**Comment by Nasnl** [comment]
And it makes a difference!

Thanks @samlhuillier !
