### ISSUE TITLE
Pipeline initialization failed for repo 'Xenova/bge-base-en-v1.5

### ISSUE THREAD

**Issue by nevellson** [reorproject/reor#81]
Indexing error: Error: Resource initialization failed: Error: Pipeline initialization failed for repo 'Xenova/bge-base-en-v1.5': TypeError: fetch failed. Please try restarting or open a Github issue.
<img width="1232" alt="iShot_2024-02-22_17 00 25" src="https://github.com/reorproject/reor/assets/5622178/ec7e8de9-e408-46a0-9bad-591b8c9ada61">

**Comment by samlhuillier** [comment]
A fix is now out to fix this proxy which makes Reor use your system's default proxy to download the embedding model. It's available here: https://github.com/reorproject/reor/releases/tag/v0.1.50
